### ISSUE TITLE
Pasek przewijania (dolny) widoczny podczas animacji

### ISSUE THREAD

**Issue by devmentor-pl** [zabula81/slider#1]
Niestety ten element nie powinien być widoczny w momencie animacji.
Najprostszym rozwiązanie to zrobić `overflow: hidden` dla elementu zawierający obrazy.
Niestety to ograniczy obszar animacji, ale moim zdaniem i tak będzie to lepsze rozwiązanie.

**Comment by frontendagnes** [comment]
Dziękuję za sugestię zupełnie nie zwróciłam na to uwagi. Problem został usunięty.
